[package]
name = "grammers-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt"] }
grammers-client = "0.3"
grammers-session = "0.3"
grammers-tl-types = "0.3"
rand = "0.8"
rpassword = "6.0"
